version: '3'
services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/defaultDB
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"